### ISSUE TITLE
HomeKit Icon

### ISSUE THREAD

**Issue by AchimPieters** [maximkulkin/esp-button#1]
At first! Thank you for you awesome work! but I have a question. When I add the button everything works just fine. The only thing is that the button icon on HomeKit stays greyed out when I toggle the button?

ps. do you have a PayPal account, I want to buy you a :coffee: for you excellent work!

**Comment by maximkulkin** [comment]
It seems that you need a [switch service](https://github.com/maximkulkin/esp-homekit/blob/master/include/homekit/characteristics.h#L135-L144) instead.

Thank you for your support. My paypal is https://www.paypal.me/MaximKulkin

**Comment by AchimPieters** [comment]
No, I know hen I Change the service to switch, the HomeKit icon allso changes. And you van see a switch Flip in the icon. But heen you toggle the button doesn’t it had to change to purpel?

https://ksassets.timeincuk.net/wp/uploads/sites/54/2017/02/Apple-Home-4.png

**Comment by AchimPieters** [comment]
Sorry doe the typo’s; typing on my iPhone and it has the dutch dictionary on. Hope you like your ☕️

**Comment by maximkulkin** [comment]
Thank you for tipping.

Actually, I'm not sure about mechanics of a button, the idea of a button is that it is usually not interact with it through Home.app. You just press physical button and it generates event that you can base your automation on.

**Comment by AchimPieters** [comment]
@maximkulkin #offtopic

Apple buys self-driving car startup Drive.ai

Congrats?

**Comment by maximkulkin** [comment]
Unfortunately, I'm not part of the deal. But I have already started in another self-driving company

**Comment by AchimPieters** [comment]
Congrats With your new Job @Plus.AI :exclamation: :thumbsup:
