### ISSUE TITLE
Mysterious False Positive by External Interference

### ISSUE THREAD

**Issue by Fonger** [maximkulkin/esp-button#2]
This works fine if I don't connect any other component on it.

However, I attach a servo mounted on a 110V AC wall switch, if the wall switch turns on, it may trigger the button event. Maybe this is caused by some kind of 110V interference? This happens almost every time. This also happens even if the servo is not functioning at all. It seems the interference can pass through servo back to esp.

I've tried active high, active low and active low with my own pull up resistor but none of them resolve the false positive.

After some debugging, I find gpio_set_interrupt is not reliable when there's some kind of external interference?

```c
#define BTN_PIN 14

void btn_intr_handler(uint8_t gpio_pin) {
  print("button interrupt!!\n")
}

void init() {
  gpio_enable(BTN_PIN, GPIO_INPUT);
  gpio_set_pullup(BTN_PIM, true, true);
  gpio_set_interrupt(BTN_PIN, GPIO_INTTYPE_EDGE_NEG, btn_intr_handler);
}
```

If I use gpio_read explicitly, this works however this is a busy wait.

```c
void button_poll_task(void *pvParameters) {
  while (true) {
    while (gpio_read(BTN_PIN) == true) { // simply wait until pin is pulled to ground
      taskYIELD();
    }
    printf("button_press!\n");
    vTaskDelay(200 / portTICK_PERIOD_MS); //debounce 200ms
  }
}

void init() {
  gpio_enable(BTN_GPIO, GPIO_INPUT);
  gpio_set_pullup(BTN_GPIO, true, true);
  xTaskCreate(&button_poll_task, "btn_task", 256, NULL, 0, NULL);
}
```

Any possible solution to solve the false positive?

**Comment by maximkulkin** [comment]
It seems the problem with schematics, not with the library. I would say, try to isolate your control circuitry from high voltage circuitry. Try to put a capacitor between button pins.

**Comment by Fonger** [comment]
Thanks. I've tried capacitor but it doesn't work. It's really weird but I give up on this configuration. ( I used servo to control the light switch) Now I use a relay.
